#!/usr/bin/env python3
"""
Plot per-segment ATE-RMSE CDF curves for Up-to-scale and Metric evaluations.

Inputs (generated by evaluate_trajectory_metrics.py):
  - up_to_scale_per_segment.csv
  - metric_per_segment.csv

Outputs:
  - cdf_ate_up_to_scale.png
  - cdf_ate_metric.png
  - (optional) combined 2-panel figure
"""

from __future__ import annotations

import argparse
import os
from typing import Dict, List, Tuple

import numpy as np


def _read_csv(path: str) -> List[dict]:
    import csv

    with open(path, "r", encoding="utf-8") as f:
        return list(csv.DictReader(f))


def _group_values(rows: List[dict], key_field: str, value_field: str) -> Dict[str, np.ndarray]:
    grouped: Dict[str, List[float]] = {}
    for r in rows:
        k = r[key_field]
        v = r.get(value_field, "")
        if v is None or v == "" or str(v).lower() == "none":
            continue
        try:
            fv = float(v)
        except Exception:
            continue
        grouped.setdefault(k, []).append(fv)
    return {k: np.asarray(v, dtype=np.float64) for k, v in grouped.items()}


def _ecdf(x: np.ndarray) -> Tuple[np.ndarray, np.ndarray]:
    x = np.asarray(x, dtype=np.float64)
    x = x[np.isfinite(x)]
    if x.size == 0:
        return np.array([]), np.array([])
    xs = np.sort(x)
    ys = np.arange(1, xs.size + 1, dtype=np.float64) / float(xs.size)
    return xs, ys


def _plot_cdf(
    grouped: Dict[str, np.ndarray],
    title: str,
    out_path: str,
    xscale: str = "linear",
    xclip: float | None = None,
    order: List[str] | None = None,
    show_median: bool = True,
) -> None:
    import matplotlib.pyplot as plt

    plt.figure(figsize=(8, 6))

    if order is None:
        order = sorted(grouped.keys())

    for name in order:
        if name not in grouped:
            continue
        vals = grouped[name]
        if xclip is not None:
            vals = vals[vals <= xclip]
        xs, ys = _ecdf(vals)
        if xs.size == 0:
            continue
        plt.plot(xs, ys, linewidth=2, label=f"{name} (n={len(vals)})")
        if show_median:
            med = float(np.median(vals))
            plt.axvline(med, linestyle=":", linewidth=1, alpha=0.25)

    plt.title(title)
    plt.xlabel("ATE-RMSE (meters)")
    plt.ylabel("CDF  (P[ATE ≤ x])")
    plt.grid(True, alpha=0.3)
    plt.legend()
    plt.xscale(xscale)
    os.makedirs(os.path.dirname(out_path), exist_ok=True)
    plt.savefig(out_path, dpi=300, bbox_inches="tight")
    plt.close()


def main() -> None:
    p = argparse.ArgumentParser()
    p.add_argument(
        "--input-dir",
        default=None,
        help="Directory containing *_per_segment.csv (default: newest eval_outputs_* in Comparative_tests).",
    )
    p.add_argument("--xscale", choices=["linear", "log"], default="linear")
    p.add_argument(
        "--xclip-metric",
        type=float,
        default=None,
        help="Optional clip for metric ATE to improve readability (e.g., 5.0).",
    )
    p.add_argument("--combined", action="store_true", help="Also save a 2-panel combined figure.")
    args = p.parse_args()

    base_dir = args.input_dir
    if base_dir is None:
        # best-effort: pick a common default if user runs from repo root
        base_dir = os.path.join(os.path.dirname(os.path.abspath(__file__)), "eval_outputs_auc3_10")

    up_csv = os.path.join(base_dir, "up_to_scale_per_segment.csv")
    met_csv = os.path.join(base_dir, "metric_per_segment.csv")
    if not os.path.exists(up_csv) or not os.path.exists(met_csv):
        raise FileNotFoundError(f"Missing CSVs in {base_dir}")

    up_rows = _read_csv(up_csv)
    met_rows = _read_csv(met_csv)

    up = _group_values(up_rows, key_field="model", value_field="ate_rmse")
    met = _group_values(met_rows, key_field="model", value_field="ate_rmse")

    # Prefer a stable method order if present
    preferred = ["VGGT", "DA3", "MapAnything", "ViPE", "Any4D"]
    order = [m for m in preferred if m in set(up.keys()).union(set(met.keys()))] + [
        m for m in sorted(set(up.keys()).union(set(met.keys()))) if m not in preferred
    ]

    _plot_cdf(
        up,
        title="Up-to-scale: per-segment ATE-RMSE CDF (Sim2 aligned)",
        out_path=os.path.join(base_dir, "cdf_ate_up_to_scale.png"),
        xscale=args.xscale,
        xclip=None,
        order=order,
    )
    _plot_cdf(
        met,
        title="Metric: per-segment ATE-RMSE CDF (raw waypoints)",
        out_path=os.path.join(base_dir, "cdf_ate_metric.png"),
        xscale=args.xscale,
        xclip=args.xclip_metric,
        order=order,
    )

    if args.combined:
        import matplotlib.pyplot as plt

        fig, axes = plt.subplots(1, 2, figsize=(14, 5), sharey=True)
        for ax, grouped, title, clip in [
            (axes[0], up, "Up-to-scale (Sim2 aligned)", None),
            (axes[1], met, "Metric (raw waypoints)", args.xclip_metric),
        ]:
            for name in order:
                if name not in grouped:
                    continue
                vals = grouped[name]
                if clip is not None:
                    vals = vals[vals <= clip]
                xs, ys = _ecdf(vals)
                if xs.size == 0:
                    continue
                ax.plot(xs, ys, linewidth=2, label=name)
            ax.set_title(title)
            ax.set_xlabel("ATE-RMSE (m)")
            ax.grid(True, alpha=0.3)
            ax.set_xscale(args.xscale)
        axes[0].set_ylabel("CDF  (P[ATE ≤ x])")
        axes[1].legend()
        out_path = os.path.join(base_dir, "cdf_ate_combined.png")
        plt.savefig(out_path, dpi=300, bbox_inches="tight")
        plt.close(fig)

    print(f"✓ Saved CDF plots into: {base_dir}")


if __name__ == "__main__":
    main()

