#!/usr/bin/env python3
"""
Plot per-segment ATE-RMSE and RTA CDF curves for Up-to-scale and Metric evaluations.

Inputs (generated by evaluate_trajectory_metrics.py):
  - up_to_scale_per_segment.csv
  - metric_per_segment.csv

Outputs:
  - cdf_ate_up_to_scale.png
  - cdf_ate_metric.png
  - cdf_rta_up_to_scale.png
  - cdf_rta_metric.png
  - (optional) combined 2-panel figure for ATE
"""

from __future__ import annotations

import argparse
import os
from typing import Dict, List, Tuple

import numpy as np


def _read_csv(path: str) -> List[dict]:
    import csv

    with open(path, "r", encoding="utf-8") as f:
        return list(csv.DictReader(f))


def _group_values(rows: List[dict], key_field: str, value_field: str) -> Dict[str, np.ndarray]:
    grouped: Dict[str, List[float]] = {}
    for r in rows:
        k = r[key_field]
        v = r.get(value_field, "")
        if v is None or v == "" or str(v).lower() == "none":
            continue
        try:
            fv = float(v)
        except Exception:
            continue
        grouped.setdefault(k, []).append(fv)
    return {k: np.asarray(v, dtype=np.float64) for k, v in grouped.items()}


def _ecdf(x: np.ndarray) -> Tuple[np.ndarray, np.ndarray]:
    x = np.asarray(x, dtype=np.float64)
    x = x[np.isfinite(x)]
    if x.size == 0:
        return np.array([]), np.array([])
    xs = np.sort(x)
    ys = np.arange(1, xs.size + 1, dtype=np.float64) / float(xs.size)
    return xs, ys


def _plot_cdf(
    grouped: Dict[str, np.ndarray],
    title: str,
    out_path: str,
    xscale: str = "linear",
    xclip: float | None = None,
    order: List[str] | None = None,
    show_median: bool = True,
    label_map: Dict[str, str] | None = None,
    style_map: Dict[str, dict] | None = None,
    xlabel: str | None = None,
    ylabel: str | None = None,
) -> None:
    import matplotlib.pyplot as plt

    # Larger fonts for paper-quality single figures
    plt.rcParams.update(
        {
            "font.size": 15,
            "axes.titlesize": 19,
            "axes.labelsize": 17,
            "xtick.labelsize": 15,
            "ytick.labelsize": 15,
            "legend.fontsize": 15,
        }
    )

    plt.figure(figsize=(8, 6))

    if order is None:
        order = sorted(grouped.keys())

    for name in order:
        if name not in grouped:
            continue
        vals = grouped[name]
        if xclip is not None:
            vals = vals[vals <= xclip]
        xs, ys = _ecdf(vals)
        if xs.size == 0:
            continue
        display_name = label_map.get(name, name) if label_map else name
        extra_style = style_map.get(name, {}) if style_map else {}
        plt.plot(xs, ys, linewidth=2, label=f"{display_name}", **extra_style)
        if show_median:
            med = float(np.median(vals))
            plt.axvline(med, linestyle=":", linewidth=1, alpha=0.25)

    # Add a bit more whitespace between text and axes
    if title:
        plt.title(title, pad=10)
    plt.xlabel(xlabel if xlabel else "ATE-RMSE (m)", labelpad=10)
    plt.ylabel(ylabel if ylabel else "CDF  (P[ATE ≤ x])", labelpad=10)
    plt.grid(True, alpha=0.3)
    plt.legend()
    plt.tick_params(axis="both", which="major", pad=6)
    plt.xscale(xscale)
    os.makedirs(os.path.dirname(out_path), exist_ok=True)
    plt.savefig(out_path, dpi=300, bbox_inches="tight")
    plt.close()


def main() -> None:
    p = argparse.ArgumentParser()
    p.add_argument(
        "--input-dir",
        default=None,
        help="Directory containing *_per_segment.csv (default: newest eval_outputs_* in Comparative_tests).",
    )
    p.add_argument("--xscale", choices=["linear", "log"], default="linear")
    p.add_argument(
        "--xclip-metric",
        type=float,
        default=None,
        help="Optional clip for metric ATE to improve readability (e.g., 5.0).",
    )
    p.add_argument("--combined", action="store_true", help="Also save a 2-panel combined figure.")
    args = p.parse_args()

    base_dir = args.input_dir
    if base_dir is None:
        # best-effort: pick a common default if user runs from repo root
        base_dir = os.path.join(os.path.dirname(os.path.abspath(__file__)), "eval_outputs_auc3_10")

    up_csv = os.path.join(base_dir, "up_to_scale_per_segment.csv")
    met_csv = os.path.join(base_dir, "metric_per_segment.csv")
    if not os.path.exists(up_csv) or not os.path.exists(met_csv):
        raise FileNotFoundError(f"Missing CSVs in {base_dir}")

    up_rows = _read_csv(up_csv)
    met_rows = _read_csv(met_csv)

    up_ate = _group_values(up_rows, key_field="model", value_field="ate_rmse")
    met_ate = _group_values(met_rows, key_field="model", value_field="ate_rmse")
    up_rta = _group_values(up_rows, key_field="model", value_field="rta_mean_deg")
    met_rta = _group_values(met_rows, key_field="model", value_field="rta_mean_deg")

    # Prefer a stable method order if present
    preferred = ["VGGT", "DA3", "MapAnything", "ViPE", "Any4D"]
    order = [m for m in preferred if m in set(up_ate.keys()).union(set(met_ate.keys()))] + [
        m for m in sorted(set(up_ate.keys()).union(set(met_ate.keys()))) if m not in preferred
    ]

    metric_label_map = {"VGGT": r"VGGT$^\dagger$"}
    metric_style_map = {"VGGT": {"linestyle": "--"}}

    # Plot ATE CDFs (no title)
    _plot_cdf(
        up_ate,
        title="",
        out_path=os.path.join(base_dir, "cdf_ate_up_to_scale.png"),
        xscale=args.xscale,
        xclip=None,
        order=order,
    )
    _plot_cdf(
        met_ate,
        title="",
        out_path=os.path.join(base_dir, "cdf_ate_metric.png"),
        xscale=args.xscale,
        xclip=args.xclip_metric,
        order=order,
        label_map=metric_label_map,
        style_map=metric_style_map,
    )

    # Plot RTA CDFs (no title)
    _plot_cdf(
        up_rta,
        title="",
        out_path=os.path.join(base_dir, "cdf_rta_up_to_scale.png"),
        xscale=args.xscale,
        xclip=None,
        order=order,
        xlabel="RTA (deg)",
        ylabel="CDF  (P[RTA ≤ x])",
    )
    _plot_cdf(
        met_rta,
        title="",
        out_path=os.path.join(base_dir, "cdf_rta_metric.png"),
        xscale=args.xscale,
        xclip=None,
        order=order,
        label_map=metric_label_map,
        style_map=metric_style_map,
        xlabel="RTA (deg)",
        ylabel="CDF  (P[RTA ≤ x])",
    )

    if args.combined:
        import matplotlib.pyplot as plt

        # Slightly larger fonts for combined figure as well
        plt.rcParams.update(
            {
                "font.size": 14,
                "axes.titlesize": 17,
                "axes.labelsize": 15,
                "xtick.labelsize": 13,
                "ytick.labelsize": 13,
                "legend.fontsize": 13,
            }
        )

        fig, axes = plt.subplots(1, 2, figsize=(14, 5), sharey=True)
        for ax, grouped, title, clip in [
            (axes[0], up_ate, "Up-to-scale (Sim2 aligned)", None),
            (axes[1], met_ate, "Metric (raw waypoints)", args.xclip_metric),
        ]:
            for name in order:
                if name not in grouped:
                    continue
                vals = grouped[name]
                if clip is not None:
                    vals = vals[vals <= clip]
                xs, ys = _ecdf(vals)
                if xs.size == 0:
                    continue
                if grouped is met_ate:
                    display_name = metric_label_map.get(name, name)
                else:
                    display_name = name
                extra_style = metric_style_map.get(name, {}) if grouped is met_ate else {}
                ax.plot(xs, ys, linewidth=2, label=display_name, **extra_style)
            ax.set_title(title, pad=8)
            ax.set_xlabel("ATE-RMSE (m)", labelpad=8)
            ax.grid(True, alpha=0.3)
            ax.set_xscale(args.xscale)
            ax.tick_params(axis="both", which="major", labelsize=13, pad=5)
        axes[0].set_ylabel("CDF  (P[ATE ≤ x])", labelpad=8)
        axes[1].legend()
        out_path = os.path.join(base_dir, "cdf_ate_combined.png")
        plt.savefig(out_path, dpi=300, bbox_inches="tight")
        plt.close(fig)

    print(f"✓ Saved CDF plots into: {base_dir}")


if __name__ == "__main__":
    main()

